pipeline {

  agent {
    kubernetes {
      yamlFile 'worker/build-agent.yaml'
      defaultContainer 'maven'
      idleMinutes 1
    }
  }

  stages {

    stage('Build') {
      when {
        changeset "**/worker/**"
      }
      parallel {
        stage('mvn compile') {
          steps {
            container('maven') {
              dir('worker') {
                sh 'mvn compile'
              }
            }
          }
        }
      }
    }

    stage('Unit Tests') {
      when {
        changeset "**/worker/**"
      }
      parallel {
        stage('mvn test') {
          steps {
            container('maven') {
              dir('worker') {
                sh 'mvn test'
              }
            }
          }
        }
      }
    }

    stage('SCA') {
      when {
        changeset "**/worker/**"
      }
      parallel {
        stage('Dependency Check') {
          steps {
            container('maven') {
              dir('worker') {
                catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                  sh 'mvn org.owasp:dependency-check-maven:check'
                }
              }
            }
          }
          post {
            always {
              archiveArtifacts allowEmptyArchive: true, artifacts: 'worker/target/dependency-check-report.html', fingerprint: true, onlyIfSuccessful: true
              //dependencyCheckPublisher pattern: 'report.xml'
            }
          }
        }
        stage('OSS License Checker') {
          steps {
            container('licensefinder') {
              dir('worker') {
                sh 'ls -al'
                sh '''#!/bin/bash --login
                        /bin/bash --login
                        rvm use default
                        gem install license_finder
                        license_finder
                      '''
              }
            }
          }
        }
      }
    }

    stage('SAST') {
      when {
        changeset "**/worker/**"
      }
      environment {
        SONAR_TOKEN = credentials('sonar-instavote-worker')
      }
      parallel {
        stage('SonarScanner') {
          steps {
            container('sonarscanner') {
              dir('worker') {
                sh "sonar-scanner -Dsonar.login=$SONAR_TOKEN -Dsonar.host.url=https://sonarcloud.io"
              }
            }
          }
        }
      }
    }

    stage('Package') {
      when {
        branch 'master'
        changeset "**/worker/**"
      }
      parallel {
        stage('Create Jarfile') {
          steps {
            container('maven') {
              dir('worker') {
                sh 'mvn package -DskipTests'
                archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
              }
            }
          }
        }
        stage('OCI image BnP') {
          steps {
            container('kaniko') {
              dir('worker') {
                sh "/kaniko/executor -f `pwd`/Dockerfile -c `pwd` --insecure --skip-tls-verify --cache=true --destination=docker.io/xvag/worker2:v${env.BUILD_ID}"
              }
            }
          }
        }
      }
    }

    stage('Image Analysis') {
      when {
        branch 'master'
        changeset "**/worker/**"
      }
      parallel {
        stage('Image Linting') {
          steps {
            container('docker-tools') {
              sh "dockle docker.io/xvag/worker2:v${env.BUILD_ID}"
            }
          }
        }
        stage('Image Scan') {
          steps {
            container('docker-tools') {
              sh "trivy image --exit-code 1 xvag/worker2:v${env.BUILD_ID}"
              //sh "trivy image xvag/worker2:v${env.BUILD_ID}"
            }
          }
        }
      }
    }

    stage('Package :latest') {
      when {
        branch 'master'
        changeset "**/worker/**"
      }
      parallel {
        stage('BnP :latest') {
          steps {
            container('kaniko') {
              dir('worker') {
                sh "/kaniko/executor -f `pwd`/Dockerfile -c `pwd` --insecure --skip-tls-verify --cache=true --destination=docker.io/xvag/worker2:latest"
              }
            }
          }
        }
      }
    }

  }
  post{
    always{
        echo 'Building multibranch pipeline for worker is completed...'
    }
  }
}
